name: SonarQube - API

on:
  push:
    branches: [ main ]
    paths:
      - 'Api/**'
      - '.github/workflows/sonar-api.yml'
  pull_request:
    paths:
      - 'Api/**'
      - '.github/workflows/sonar-api.yml'

jobs:
  scan-api:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17 (required by SonarScanner)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Sonar BEGIN (API)
        working-directory: Api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ..\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"insy7315_INSY7315-A-Team" `
            /o:"insy7315" `
            /d:sonar.projectName="INSY7315-API" `
            /d:sonar.cs.opencover.reportsPaths="**\coverage.opencover.xml" `
            /d:sonar.token="${{ env.SONAR_TOKEN }}"
      - name: Restore (API)
        working-directory: Api
        run: dotnet restore

      - name: Build (API)
        working-directory: Api
        run: dotnet build --no-restore --configuration Debug

      - name: Detect test projects
        id: detect_tests
        working-directory: Api
        shell: pwsh
        run: |
          $tests = Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -match 'Test' -or $_.Name -match 'Tests' }
          if ($tests) {
            echo "hasTests=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "hasTests=false" >> $env:GITHUB_OUTPUT
      - name: Run tests with coverage
        if: steps.detect_tests.outputs.hasTests == 'true'
        working-directory: Api
        shell: pwsh
        run: |
          $tests = Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -match 'Test' -or $_.Name -match 'Tests' }
          foreach ($proj in $tests) {
            dotnet test $proj.FullName --no-build `
              /p:CollectCoverage=true `
              /p:CoverletOutputFormat=opencover `
              /p:CoverletOutput=./TestResults/coverage.opencover.xml
      - name: Sonar END (API)
        working-directory: Api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ..\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"
