name: SonarQube Web Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    name: SonarQube Scan - Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install dependencies
        run: npm install
        working-directory: ./web   # adjust if your web project folder is named differently

      - name: Build and analyze Web
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WEB }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=your-org_web \
            -Dsonar.organization=your-org \
            -Dsonar.host.url=https://sonarcloud.io
